### ISSUE TITLE
directory with code not mentioned in cabal file is included by ghcide

### ISSUE THREAD

**Issue by andrewufrank** [haskell/ghcide#648] opened 2020-06-18 16:35 UTC
I have constructed a minimal project to learn how to use ghcide. The directory includes a main and a library. It contains an additioanl directory `tests` which is not included in the cabal file (and not ready to compile). `ghcide` includes these files, which it should not. 

The messages are:

 `Could not find module ‘Test.Framework’
  It is not a module in the current program, or in any known package. `

and at the end it says:  `Completed (4 files worked, 3 files failed)`

The code is `https://github.com/andrewufrank/minimalForTest.git `  there is a master branch  with the `tests` directory and another one `no-tests-dir` which has no `tests` directory and thus `ghcide` works perfectly.

**Comment by fendor** [comment] 2020-06-18 18:23
Hi! 

So, essentially the problem is that build-tools do not give us the information we need to really know when a file is part of package.
In this case, due to the existence of `stack.yaml`, we assume that you are using stack for building the project. 
When you open a file, we try to find the compilation options required for this file.
We try to find the compilation flags by executing `stack repl` and intercept the options that are passed to `ghci`. 
In this case, `stack repl` succeeds, since it isnt even aware of the filepath we are looking for. 
Note, we can not use `stack repl tests/Testing.hs`, because stack will only compute a partial module graph, which you generally do not want! 

When you are using `cabal`, the behaviour is as expected (delete stack.yaml)
```bash
> hie-bios flags tests/Testing.hs
Failed to show flags for "tests/Testing.hs": 
["Failed to parse result of calling cabal"
,""
,"cabal: Unknown target 'tests/Testing.hs'.\nThe package TestSimple has no file target 'tests/Testing.hs'.\n\n\n"
,""
]
``` 

However, what you actually want is to ignore certain directories. You can achieve that by using a configuration file `hie.yaml` and specify how to load you project. (Reference https://github.com/mpickering/hie-bios)
For your particular project, the `hie.yaml` you want looks like:
```yaml
cradle:
  multi:
    - path: ./tests
      config:
        cradle:
          none: # Do not even attempt to load this directory
    - path: ./ # for everything else, load it with stack
      config:
        cradle:
          stack:
```

So, this configuration tells ghcide (and Haskell Language Server and Haskell IDE Engine, all three of those use this format) to not attempt to load anything from `./tests` and for everything else, it should use `stack` (or essentially `stack repl`).
If `stack repl` is not enough to load your project (usually when you have multiple executables), you can specify an exact mapping from a directory to a component. For your project:

```yaml
cradle:
  multi:
    - path: ./tests
      config:
        cradle:
          none: # Do not even attempt to load this directory
    - path: ./ # for everything else, load it with stack
      config:
        cradle:
          stack:
            # Special short-hand syntax since you need it quite often
            - path: ./
              component: "SimpleTest:lib"
            - path: ./src/ClassMain.hs
              component: "SimpleTest:exe:foo"
```
Whenever you trying to `./src/ClassMain.hs`, we essentially perform a `stack repl SimpleTest:exe:foo` to load the component.
This component syntax exists for both cabal and stack and is slightly different for each :).

This behaviour cannot easily be improved unless the different tools give us the information we need to actually know the full project.

**Comment by codygman** [comment] 2020-06-19 00:25
@fendor I don't think that syntax works unless something else is wrong with my project. Here's the output, hopefully this is a concise explanation of the relevant details. It's using [this repo](https://github.com/codygman/haskell-nix-stack-workflow/tree/0ca4bf7b27dbdfa60cc1ccf8afd6a3bc79d1fe54).

```
[cody@nixos:~/code/haskell-nix-stack-workflow]$ ghcide
ghcide version: 0.2.0 (GHC: 8.8.3) (PATH: /nix/store/anx0pkkg78cb6nwk7qwibxjlsinciqaa-ghcide-exe-ghcide-0.2.0/bin/ghcide)
Ghcide setup tester in /home/cody/code/haskell-nix-stack-workflow.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/4: Finding files to test in /home/cody/code/haskell-nix-stack-workflow
Found 4 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
[INFO] Consulting the cradle for "/home/cody/code/haskell-nix-stack-workflow/test/Spec.hs"
[INFO] Consulting the cradle for "/home/cody/code/haskell-nix-stack-workflow/Setup.hs"
> Using main module: 1. Package `myproj' component myproj:exe:myproj-exe with main-is file: /home/cody/code/haskell-nix-stack-workflow/app/Main.hs
> Building all executables for `myproj' once. After a successful build of all of them, only specified executables will be rebuilt.
> myproj> configure (lib + exe)
> Configuring myproj-0.1.0.0...
> myproj> initial-build-steps (lib + exe)
> The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
> Configuring GHCi with the following packages: myproj
> /home/cody/code/haskell-nix-stack-workflow/.stack-work/install/x86_64-linux/d3c82d6bc945faf73d603efcfff7cea111961b91cca00cdae6850ef9f45513a6/8.8.3/pkgdb:/home/cody/.stack/snapshots/x86_64-linux/d3c82d6bc945faf73d603efcfff7cea111961b91cca00cdae6850ef9f45513a6/8.8.3/pkgdb:/nix/store/zqa7a1pwqnyl8yr1bqclcvi9z3jz793d-ghc-shell-for-myproj-config/lib/ghc-8.8.3/package.conf.d
[INFO] Using interface files cache dir: /home/cody/.cache/ghcide/main-32f86eced2ba5d89e43fb8830fe4c661bc922af2
[INFO] Making new HscEnv[main]
File:     /home/cody/code/haskell-nix-stack-workflow/Setup.hs
Hidden:   no
Range:    1:7-1:26
Source:   not found
Severity: DsError
Message: 
  Could not load module ‘Distribution.Simple’
  It is a member of the hidden package ‘Cabal-3.0.1.0’.
  You can run ‘:set -package Cabal’ to expose it.
  (Note: this unloads all the modules in the current scope.)
Files that failed:
 * /home/cody/code/haskell-nix-stack-workflow/Setup.hs
 * /home/cody/code/haskell-nix-stack-workflow/test/Spec.hs

Completed (2 files worked, 2 files failed)
```

**Comment by codygman** [comment] 2020-06-19 00:30
So one is my issue from  mpickering/hie-bios#201 I think. The other though, ignoring the test directory, I think could be a separate issue?

**Comment by fendor** [comment] 2020-06-19 10:26
>    Files that failed:
>     * /home/cody/code/haskell-nix-stack-workflow/Setup.hs
>     * /home/cody/code/haskell-nix-stack-workflow/test/Spec.hs

The file `test/Spec.hs` did not fail, this is just not displayed correctly by ghcide. See https://github.com/digital-asset/ghcide/blob/master/exe/Main.hs#L200.

So, try actually opening the file, it should be working? 

The Setup.hs can just not be loaded.

**Comment by andrewufrank** [comment] 2020-06-24 14:04
Thank you for the answer; I learned something new. I do not see immediately why you are not looking at the cabal or package.yaml file to see which components are not used currently.

**Comment by fendor** [comment] 2020-06-24 14:37
> why you are not looking at the cabal or package.yaml file to see which components are not used currently.

We try, but neither stack nor cabal expose an interface where you can actually find out which components are active and to which component a given filepath belongs to. Our approach is, therefore, an approximation, that needs be fixed in the build-tools themselves.

**Comment by pepeiborra** [comment] 2020-12-31 21:01
Closing as there is not a clear action path. Please open a new ticket in haskell/haskell-language-server if there are still any issues

**Closed by pepeiborra** 2020-12-31 21:01 UTC
