### ISSUE TITLE
ghcide is missing functionality for (lorri+direnv+emacs-direnv) in emacs:

### ISSUE THREAD

**Issue by zeta-00** [haskell/ghcide#528] opened 2020-04-15 04:58 UTC
with this shell.nix: https://dpaste.org/NcYb , when i run nix-shell in terminal, emacs opens up into the directory and ghcide is able to recognize modules when i try to import, but when i try to use (lorri+direnv+emacs-direnv) in emacs, ghcide works but it's not able to recognize modules, like when i try to import Yesod for example.

**Comment by ndmitchell** [comment] 2020-05-18 15:20
So it works from a Nix shell, but doesn't otherwise? Is the cause that direnv isn't replicating the Nix shell properly? I have no idea how you'd test that.

**Comment by fendor** [comment] 2020-05-18 16:20
I am using ghcide in roughly that setup(vscode instead of emacs). I use the nix-shell to set up the environment and ghcide is on my path. That setup works great for me.

**Comment by willbush** [comment] 2020-05-30 07:53
I've had some success getting (lorri+direnv+emacs-direnv) in emacs to work. Can you share the relevant bits of your Emacs config and that shell.nix again (link is broken)?

**Comment by zeta-00** [comment] 2020-05-30 19:44
it turns out that i was missing the `lorri shell` command, now ghcide is able to pick up on shell.nix's environment variables setup in shellHook, also, for my ihaskell setup i needed to place `use_nix shell.nix` inside of .envrc in order for it to work, just thought i'd share that piece of information as well.

other than a few edge cases that i need to figure out, everything seems to be working now, thanks for the help everyone.

go ahead and close this issue.

**Comment by zeta-00** [comment] 2020-05-30 19:59
and apologies, dpaste deletes pastebin's after a certain amount of time, here's the shell.nix that i am currently using for haskell development:


let
  pkgs = import <nixpkgs> {};
in
with pkgs;
mkShell
  {
    buildInputs = with pkgs;
      [
        (haskell.packages.ghc883.ghcWithHoogle (hpkgs: with hpkgs;
          [
            ghcid
            cabal-install
          ]))
        
        # ghcide-nix installation:
        (import (builtins.fetchTarball "https://github.com/cachix/ghcide-nix/tarball/master") {}).ghcide-ghc883
        
      ]; # end of buildInputs


    shellHook =
      ''
         export EDITOR=emacs;

         export HIE_HOOGLE_DATABASE="$(cat $(which hoogle) | sed -n -e 's|.*--database \\(.*\\.hoo\\).*|\\1|p')";
         export NIX_GHC="$(which ghc)";
         export NIX_GHCPKG="$(which ghc-pkg)";
         export NIX_GHC_DOCDIR="$NIX_GHC/../../share/doc/ghc/html";
         export NIX_GHC_LIBDIR="$(ghc --print-libdir)";
      '';
    
  } # end of mkShell

**Comment by jneira** [comment] 2020-10-05 08:34
Had been some improvements for use ghcide in nix environments, @zeta-00 could you check if you continue experiencing the issue with lastest ghcide?

**Comment by pepeiborra** [comment] 2021-01-01 19:58
closing this as ghcide is not the problem here

**Closed by pepeiborra** 2021-01-01 19:58 UTC
Labels: os: nixos, status: needs confirmation, type: bug
