### ISSUE TITLE
Unable to get ghcide working Error ghcide: <command line>: can't load .so/.DLL

### ISSUE THREAD

**Issue by mayank-17** [haskell/ghcide#404] opened 2020-02-04 16:14 UTC
`ghcide version: 0.0.6 (GHC: 8.6.5) (PATH: /home/mayanks/.local/bin/ghcide) (GIT hash: 2f5d0d3e69abb5f321bf28b1049ae7a7fc9f619e)
Ghcide setup tester in /home/mayanks/work/transporter.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /home/mayanks/work/transporter
Found 7 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading ./hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: <command line>: can't load .so/.DLL for: /nix/store/qn76sklvyalzw9ilnxz6sh0020gl2qn6-glibc-2.27/lib/libpthread.so (/nix/store/qn76sklvyalzw9ilnxz6sh0020gl2qn6-glibc-2.27/lib/libpthread.so.0: undefined symbol: __libc_vfork, version GLIBC_PRIVATE)
`

**Comment by domenkozar** [comment] 2020-02-05 05:20
What OS are you using?

**Comment by mayank-17** [comment] 2020-02-08 09:19
Manjaro i3

**Comment by epeery** [comment] 2020-02-27 23:50
Any updates on this? Having the same issue.

**Comment by domenkozar** [comment] 2020-02-28 08:01
@epeery what OS?

**Comment by epeery** [comment] 2020-02-28 16:43
Arch Linux

**Comment by epeery** [comment] 2020-02-28 16:46
One interesting thIng I might note is that when I add a cabal.project file to the root of the project the error changes to:

Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: CradleError (ExitFailure 1) ["Failed to parse result of calling cabal","","cabal: Unrecognised target syntax for ''.\n\n",""]

**Comment by domenkozar** [comment] 2020-03-02 09:05
Seems to be also present on https://github.com/mpickering/haskell-ide-engine/issues/63

**Comment by domenkozar** [comment] 2020-03-02 09:09
Could you check if `LD_PRELOAD` contains something and if it does run ghcide with `LD_PRELOAD= ghcide ...`

If that's not the case, it just system glibc interfering with Nix glibc, something that https://github.com/NixOS/nixpkgs/pull/31263 wants to solve.

**Comment by epeery** [comment] 2020-03-02 14:52
Running `LD_PRELOAD=ghcide ghcide` gives me the error:

ERROR: ld.so: object 'ghcide' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Seems like that thread you linked is likely the solution. Hopefully it gets merged soon :)

**Comment by domenkozar** [comment] 2020-03-02 14:58
`LD_PRELOAD= ghcide` is the correct command - there's a space between equal sign and ghcide.

**Comment by epeery** [comment] 2020-03-02 15:44
Ah got it. My bad. Thanks.
The LD_PRELOAD error goes away but the can't load .so/.DLL error persists.

**Comment by fabioluz** [comment] 2020-03-03 23:05
I'm having the same issue but in my case the message is:
`can't load .so/.DLL for: libgmp.so (libgmp.so: cannot open shared object file: No such file or directory)`

I'm using Ubuntu 18.04.2 LTS via Windows Subsystem Linux

The package in mentioned is located at `/usr/lib/x86_64-linux-gnu/` However, it seems GHC cannot find it.

Inside `/etc/ld.so.conf.d` I have two files: `libc.conf  x86_64-linux-gnu.conf`. The latter contains the path to `/usr/lib/x86_64-linux-gnu/`. I also tried adding path to the former, no change. The GHC still cannot find libgmp.so.

Any ideas?

**Comment by domenkozar** [comment] 2020-03-04 10:21
Could I ask if you're using vscode and if so, if it's installed with Nix? This applies to everyone.

**Comment by domenkozar** [comment] 2020-03-04 10:59
@fabioluz could you run `nix-store -qR /nix/store/xhg5lzac77x3y6ww54qjrvi3ygyjxzq9-ghcide-0.1.0-exe-ghcide`

**Comment by fabioluz** [comment] 2020-03-04 12:20
@domenkozar Yes, I'm using VSCode, it was not installed with Nix. Only ghcide was installed with Nix. Anyway, I get the same error if I run `ghcide` inside the project folder, so it should not be related to vscode, right?

The project was generated by Stack, which is was not installed with Nix.

The command you mentioned above showed a bunch of packages, more than 100.
```
/nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27
/nix/store/jxny7lfjvxwxli237wp3fl09wll0jlfh-gcc-7.4.0-lib
/nix/store/f0wi5c6j4zl8idrd6qw3bsis7cmdy7j7-gmp-6.1.2
...
```

**Comment by domenkozar** [comment] 2020-03-04 12:29
Thanks! Can you also run `echo $LD_LIBRARY_PATH`?

**Comment by domenkozar** [comment] 2020-03-04 13:04
Since this happens when loading GHC session, most likely glibc mismatch comes between ghc and ghcide. Maybe ghcide should just pin ghc since versions need to be matched anyway.

**Comment by epeery** [comment] 2020-03-04 15:04
> Could I ask if you're using vscode and if so, if it's installed with Nix? This applies to everyone.

No I’m using Neovim which I installed from the Arch package repos.

**Comment by fabioluz** [comment] 2020-03-04 18:09
> Thanks! Can you also run `echo $LD_LIBRARY_PATH`?

It does not show anything. Empty line.

> I'm happy to help debug this if someone allows me to https://tmate.io/ and use audio :)
Sure! I can do it in around 4 hours from now. Let me know when we can do it.

**Comment by domenkozar** [comment] 2020-03-05 10:16
I'm in CET, so anytime withing working hours will do :)

**Comment by epeery** [comment] 2020-03-05 13:41
I'm also available if that helps. Today is pretty open for me

**Comment by acowley** [comment] 2020-03-07 19:45
I just started seeing this on NixOS, too. @domenkozar's suggestion about a glibc mismatch seems likely as my cachix-installed ghcide is now saying,

```
Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: <command line>: can't load .so/.DLL for: /nix/store/5ar4gjxiykc3vpn40whgsd0cgqxgfng7-ghc-8.6.5/lib/ghc-8.6.5/ghc-prim-0.5.3/libHSghc-prim-0.5.3-ghc8.6.5.so (/nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libm.so.6: version `GLIBC_2.29' not found (required by /nix/store/5ar4gjxiykc3vpn40whgsd0cgqxgfng7-ghc-8.6.5/lib/ghc-8.6.5/ghc-prim-0.5.3/libHSghc-prim-0.5.3-ghc8.6.5.so))
```

**Comment by fabioluz** [comment] 2020-03-08 18:26
Let me know how I can give you the session id for https://tmate.io/

**Comment by domenkozar** [comment] 2020-03-10 14:53
@acowley can you investigate if $LD_LIBRARY_PATH is set somewhere?

**Comment by domenkozar** [comment] 2020-03-14 21:43
I've updated https://github.com/cachix/ghcide-nix to be built with glibc-2.30, could everyone using it try again?

**Comment by epeery** [comment] 2020-03-16 17:19
@domenkozar That seems to have fixed it for me. Thanks!

**Comment by fabioluz** [comment] 2020-03-17 00:58
@domenkozar It is working for me as well. Thanks!

**Comment by onixie** [comment] 2020-03-18 02:54
I still encountered some issues on Ubuntu 18.04 using nix. 
Most of the files are fine except one of those with stuffs using QuasiQuotes and TemplateHaskell. 
The log is as following:

```
[nix-shell:~/workdir/argus]$ ghcide
ghcide version: 0.1.0 (GHC: 8.6.5) (PATH: /nix/store/02wcifqr53wjs1m5vn670b1avfy071az-ghcide-0.1.0-exe-ghcide/bin/ghcide)
Ghcide setup tester in /home/shen/workdir/argus.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /home/shen/workdir/argus
Found 9 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Implicit cradle for /home/shen/workdir/argus
Cradle {cradleRootDir = "/home/shen/workdir/argus", cradleOptsProg = CradleAction: Default}

Step 4/6, Cradle 1/1: Loading GHC Session

Step 5/6: Initializing the IDE

Step 6/6: Type checking the files
File:     /home/shen/workdir/argus/src/Model.hs
Hidden:   no
Range:    1:0-100001:0
Source:   typecheck
Severity: DsError
Message: 
  Unexpected usage error
  can't load .so/.DLL for: /nix/store/siks2gcfwx6qwh27m7c5r5lixcr621bd-glibc-2.27/lib/libpthread.so
  (/nix/store/siks2gcfwx6qwh27m7c5r5lixcr621bd-glibc-2.27/lib/libpthread.so.0: undefined symbol:
  __libc_vfork, version GLIBC_PRIVATE)
Files that failed:
 * /home/shen/workdir/argus/src/Model.hs

Completed (8 files worked, 1 file failed)

[nix-shell:~/workdir/argus]$ nix-store -qR /nix/store/02wcifqr53wjs1m5vn670b1avfy071az-ghcide-0.1.0-exe-ghcide/bin/ghcide | grep glibc
/nix/store/sc7lh1dhvd7fg28d7dxwsqzfcinnr6j5-glibc-2.30
/nix/store/ad115wnlpndz5xkkvz19k2ihsb5cdqpz-glibc-2.30-bin
/nix/store/bq2ycrgyzi3zkq2mwb3j46a684smqxcr-glibc-2.30-dev

[nix-shell:~/workdir/argus]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5

```

**Comment by domenkozar** [comment] 2020-03-18 09:16
Could you run `nix-store -qR $(which ghc) | grep glibc`

**Comment by gvolpe** [comment] 2020-03-18 11:10
I had this same issue as well, and I've been following this thread. After updating `ghcide` this issue is gone, but another issue is back:

```
Step 4/6, Cradle 1/1: Loading GHC Session
> Resolving dependencies...
> Build profile: -w ghc-8.6.5 -O1
> In order, the following will be built (use -v for more details):
>  - shopping-cart-0.1.0.0 (lib) (configuration changed)
> Configuring library for shopping-cart-0.1.0.0..
> Warning: The 'license-file' field refers to the file 'LICENSE' which does not
> exist.
> Preprocessing library for shopping-cart-0.1.0.0..
ghcide: <command line>: cannot satisfy -package-id aeson-1.4.6.0-Em7rwiOS5bO6ogTsCliW9g
    (use -v for more information)
```

I can't seem to get around this `cannot satisfy -package-id` error. Any hints?

I'm running `ghcide` within a `nix-shell` because I'm on Ubuntu, and it doesn't work outside of a Nix shell.

**Comment by gvolpe** [comment] 2020-03-18 11:22
Nevermind, I managed to fix it with these exports:

```
export NIX_GHC="$(which ghc)"
export NIX_GHCPKG="$(which ghc-pkg)"
export NIX_GHC_DOCDIR="$NIX_GHC/../../share/doc/ghc/html"
export NIX_GHC_LIBDIR="$(ghc --print-libdir)"
```

Got them from this issue: https://github.com/mpickering/hie-bios/issues/25

**Comment by onixie** [comment] 2020-03-23 01:55
@domenkozar 
Here is output of the commands. I guess it means my ghc is still using the old glibc.
```
[nix-shell:~/workdir/argus]$ nix-store -qR $(which ghc) | grep glibc
/nix/store/siks2gcfwx6qwh27m7c5r5lixcr621bd-glibc-2.27
/nix/store/ngf4xva3wvw1m0pb84v9h4jgl784lxkh-glibc-2.27-bin
/nix/store/yjdnj9pcjgb09xif4ngmf13vb8npklys-glibc-2.27-dev

[nix-shell:~/workdir/argus]$ nix-store -qR /nix/store/02wcifqr53wjs1m5vn670b1avfy071az-ghcide-0.1.0-exe-ghcide/bin/ghcide | grep glibc
/nix/store/sc7lh1dhvd7fg28d7dxwsqzfcinnr6j5-glibc-2.30
/nix/store/ad115wnlpndz5xkkvz19k2ihsb5cdqpz-glibc-2.30-bin
/nix/store/bq2ycrgyzi3zkq2mwb3j46a684smqxcr-glibc-2.30-dev
```

Maybe it's a question out of ghcide. How can I force my ghc to link with glibc-2.30 by default? I'm using the nixpkgs-unstable channel.

**Comment by domenkozar** [comment] 2020-03-23 12:01
Seems like you're using outdated version of nixpkgs-unstable channel. `nix-channel --update` and reinstalling ghc should do it.

**Comment by onixie** [comment] 2020-03-24 02:10
I realized that I have to actually run `sudo /nix/var/nix/profiles/default/bin/nix-channel --update` due to the use of nix-daemon/multi-user configuration of nix and problem solved. Thanks.

**Comment by mayank-17** [comment] 2020-03-31 07:31
I managed to fix it with these exports:

export NIX_GHC
export NIX_GHCPK
export NIX_GHC_LIBDIR
export NIX_GLIBC_PRIVATE

**Comment by willbush** [comment] 2020-05-24 08:12
None of the export stuff worked for me. What helped me with this issue was found here: https://github.com/digital-asset/ghcide/issues/538

ghcide is in nixpkgs now:

```
nix-repl> pkgs = import <nixpkgs> {}
nix-repl> pkgs.haskell.packages.ghc883.ghcide
«derivation /nix/store/5kx45z9b8xvvbacq724ivpsq882m0g91-ghcide-0.1.0.drv»
```
Since the issue is due to mismatched glibc versions one can avoid the issue by including ghcide in the `shell.nix` on a per project basis assuming you're using GHC provided by the `shell.nix` from nixpkgs and not [haskell.nix](https://github.com/input-output-hk/haskell.nix).

**Comment by razvan-flavius-panda** [comment] 2020-05-31 01:53
@willbush how did you include `ghcide` in your `shell.nix` ? I have the following issue: https://github.com/haskell/haskell-ide-engine/issues/1781

**Comment by willbush** [comment] 2020-05-31 02:25
@razvan-flavius-panda I did it in [this repo](https://github.com/willbush/exercises/tree/master/haskell-exercises). Specifically [here](https://github.com/willbush/exercises/blob/f536e9ebde3c05b380d7bd8c561c6dc23b416427/haskell-exercises/default.nix#L52).

That nix expression was based on a template I found here: https://github.com/jwiegley/hello There's a lot of ways to write `shell.nix` for Haskell projects and I'm definitely not sure what the best way to do it. However, I do prefer to pin nixpkgs to a specific version using [niv](https://github.com/nmattia/niv).

Here are some links I've been collecting on the topic:

  - https://github.com/Gabriel439/haskell-nix
  - https://www.fosskers.ca/blog/nix-en.html
  - https://www.haskell.org/cabal/users-guide/nix-integration.html
  - https://cah6.github.io/technology/nix-haskell-1/
  - https://cah6.github.io/technology/nix-haskell-2/
  - https://discourse.nixos.org/t/nix-haskell-development-2020/6170

    also see:
    https://www.reddit.com/r/haskell/comments/fp0g4n/nix_haskell_development_2020_howto/

The last one might be the most up-to-date. I've only skimmed it so far.

**Comment by jneira** [comment] 2020-09-24 10:19
@domenkozar  not sure if lastest version of ghcide could have fix this, or if we could do something in ghcide to fix it, so i will close this if nobody disagree

**Closed** 2021-01-01 20:14 UTC
Labels: os: nixos, status: needs confirmation, type: bug, type: setup
