### ISSUE TITLE
Honor default-extensions in a stack project

### ISSUE THREAD

**Issue by jvliwanag** [haskell/ghcide#190] opened 2019-11-11 09:40 UTC
Default extensions may be defined in a stack project's package.yaml. These should be honored when parsing source files.

**Comment by cocreature** [comment] 2019-11-11 09:56
I think they already should be. Are you sure you are using the stack cradle?

**Comment by jvliwanag** [comment] 2019-11-11 14:54
Trying to work on [spago]( https://github.com/spacchetti/spago) which is ghc-8.4.4, so I had to build with ghcide for ghc 8.4.4.

I didn't have any `hie.yaml` defined. But I did try creating the file and setting it to `cradle: {stack}` but that made no change. Not sure if that's how you specify a cradle.

Took a peek at what `stack repl` does within the project and discovered there were two executables. Tried commenting out one executable but that didn't make any difference.

Currently trying out the current master of ghcide which currently is 7a215d2.

**Comment by ndmitchell** [comment] 2020-01-27 15:28
I think this should definitely work with hie-bios and a Stack cradle. Keen to know if that's not the case with HEAD or 0.0.6 (nothing has changed in a while - as @cocreature says, it should always have worked).

**Comment by domenkozar** [comment] 2020-01-28 05:24
I'm using default-extensions via cabal and it works.

**Comment by christiaanb** [comment] 2020-02-12 10:36
I'm having similar issues with cabal. When I add the following `hie.yaml` file to the root of: https://github.com/clash-lang/clash-compiler:

```yaml
cradle:
  cabal:
    component: "lib:clash-prelude"
```

I get loads of errors because the default extensions in `clash-prelude/clash-prelude.cabal` are not picked up.

**Comment by christiaanb** [comment] 2020-02-12 11:27
SafeHaskell issue reported separately at: https://github.com/digital-asset/ghcide/issues/424

**Comment by jneira** [comment] 2020-09-15 08:07
@jvliwanag can you reproduce it with a newer ghcide version?

**Comment by jneira** [comment] 2020-12-29 15:44
Closing optimistically, @jvliwanag feel free to open a new one in the haskell-language-server project if you continue hitting it

**Closed by jneira** 2020-12-29 15:44 UTC
Labels: status: needs confirmation, status: needs repro, type: bug
