### ISSUE TITLE
Multi-component failing on WIN10

### ISSUE THREAD

**Issue by tuomohopia** [haskell/ghcide#605] opened 2020-06-03 16:25 UTC
I can't get multi-component setup working with any `hie.yaml` configuration that I've tried.

I just installed the latest `ghcide` with:
```sh
stack --resolver lts-15.15 install
```

Now , when I define `hie.yaml` like this:
```yaml
cradle:
  stack:
    - path: "./src"
      component: "my-api:lib"
    - path: "./test"
      component: "my-api:test:integration-tests"
```

VSCode acts as if no ghcide installed. Its Output panel for `ghcide` gives me this:
https://pastebin.com/NZXCbAHH

Running `ghcide` in the project folder in Powershell terminal gives me this:
https://pastebin.com/wkMsuGT5

For the record, when I just specify the `hie.yaml` file as:
```
cradle: {stack: {component: "my-api:lib" }}
```
It works fine. But just for the `lib` files inside my `src`, not the test folder. Basically works as a single-component setup this way.

I'm on
* WIN10
* Vscode
* stack, but specify project with a `.cabal` file

Based on discussions on Slack I suspect this may be a WIN10 specific problem.

**Comment by mpickering** [comment] 2020-06-03 17:55
Actually this might be #574 which is caused by stack not listing all the dependencies correctly for a component.

**Comment by mpickering** [comment] 2020-06-03 18:39
I don't think the first problem is actually a problem. 

> The second problem I suppose we can't do anything about.

@tuomohopia On the contrary, you can just prepare a patch to fix the issue in stack!

I don't think this is a WIN10 specific issue. i

**Comment by jneira** [comment] 2020-09-16 12:30
@tuomohopia I cant reproduce the error in my windows 10 with lastest ghcide, so i am gonna to close this, feel free to reopen if you continue experiencing the issue

**Closed by jneira** 2020-09-16 12:30 UTC
Labels: os: windows, type: bug, type: setup
