### ISSUE TITLE
How to show warnings?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/ghcide#200] opened 2019-11-16 12:23 UTC
I'm using Emacs 26.3 and the lsp-ui install instructions on the ghcide README.

When I first set up `ghcide` a few hours ago it was showing warnings with an orange underline.  In fact, it was showing warnings that I didn't even have configured in my project's `.cabal` file.  It's since stopped showing any warnings at all.  Ideally I'd like it to show the warnings configured in my `.cabal` file.  How do I get it to do that?

**Comment by cocreature** [comment] 2019-11-16 17:35
It already should pick up the warnings that you defined in your cabal file, at least if you use the cabal or stack cradles. There are some warnings that we currently don’t produce due to us not running the desugarer, in particular, incomplete patterns is part of those. See #107

**Comment by Ciantic** [comment] 2019-11-18 23:29
I actually have the same problem, running

```stack exec ghcide``` gives warnings

But using from VSCode it only gives errors (and warnings on *some* files).

**Comment by Ciantic** [comment] 2019-11-19 00:07
How about closing this in favor of #107?

**Comment by tomjaguarpaw** [comment] 2019-11-19 07:17
I'm not sure this is a case of #107.  I'll have to verify when I get some time.

**Comment by jneira** [comment] 2020-09-16 09:29
This could be a duplicate of #107 and/or #524, so i am gonna close it, @tomjaguarpaw feel free to reopen if it is not the case

**Closed by jneira** 2020-09-16 09:29 UTC
Labels: type: bug
