### ISSUE TITLE
Adding +RTS to ghci-options fails with an error

### ISSUE THREAD

**Issue by csasarak** [haskell/ghcide#136] opened 2019-09-25 18:45 UTC
I had some `+RTS ... -RTS` options set for GHC in the `ghc-options` section of my `package.yaml` file. Running `ghcide` in that directory fails with `ghcide: target ‘+RTS’ is not a module name or a source file` The full output is:

```
`Step 1/6: Finding files to test in /Users/<user>/<project>
Found 601 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Implicit cradle for /Users/user/project
Cradle {cradleRootDir = "/Users/user/project", cradleOptsProg = CradleAction: stack}

Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: target ‘+RTS’ is not a module name or a source file
```

**Comment by ndmitchell** [comment] 2019-09-25 19:11
Thanks, a great error report. This is an issue in the underlying `hie-bios`. CC @mpickering. @cocreature - is move issue available to you as a maintainer?

**Comment by cocreature** [comment] 2019-09-26 06:21
I can’t move issues to repositories where I don’t have commit access.

**Comment by csasarak** [comment] 2019-10-03 20:46
@ndmitchell I have noticed that the problem doesn't occur when I use haskell-ide-engine. If it's more appropriate I can refile a bug with the hie-bios folks though. 

Thanks!

**Comment by ndmitchell** [comment] 2019-10-04 10:27
@csasarak - `hie-bios` isn't used by `haskell-ide-engine`, which will be the reason it doesn't happen there.

**Comment by AlexeyRaga** [comment] 2019-11-19 00:20
Having the same issue, would be great to have it resolved ;)

**Comment by csasarak** [comment] 2019-12-14 00:21
I've re-created this in `hie-bios` https://github.com/mpickering/hie-bios/issues/102.  I am going to try to fix this in there. But I will leave it for this project's maintainers to decide if they want to keep this issue open for reference.

**Comment by rjmk** [comment] 2020-06-11 03:12
The corresponding issue seems to have been closed in hie-bios, and ghcide uses a version of hie-bios with the fix, but I still observe the error

**Comment by fendor** [comment] 2020-06-11 07:54
@rjmk Can you provide an example project?

**Comment by rjmk** [comment] 2020-06-11 19:13
Here we go: https://github.com/rjmk/ghcide-rts-repro

I grabbed the RTS invocation from the user guide, so don't think that's the problem

**Comment by fendor** [comment] 2020-06-11 20:12
Can reproduce.
Example flags:
```
[...,"+RTS -H32m -S -RTS",...]
```
I think the hie-bios filter logic assumes `["+RTS", "-H32m", "-S", "-RTS"]`
https://github.com/mpickering/hie-bios/blob/master/src/HIE/Bios/Cradle.hs#L461

**Comment by fendor** [comment] 2020-06-11 20:22
PR: https://github.com/mpickering/hie-bios/pull/197

**Comment by jneira** [comment] 2020-09-15 07:32
This should be fixed by the pr linked above, @csasarak feel free to reopen it that is not the case

**Closed by jneira** 2020-09-15 07:32 UTC
